# test vectors for DSPTEST.PRG: y = x^e mod n, checked by Python
import random
random.seed(7)
out = ["/* generated by tests/dsp/gen.py */", "typedef struct { int bits; unsigned long e; const unsigned char *n, *x, *y; } VEC;"]
vecs = []
for k, (bits, e) in enumerate([(1024, 65537), (2048, 65537), (2048, 3), (3072, 65537), (4096, 65537), (4096, 3), (2047, 65537)]):
    n = random.getrandbits(bits) | (1 << (bits - 1)) | 1
    x = random.randrange(n)
    y = pow(x, e, n)
    nb = (bits + 7) // 8
    for name, v in (("n", n), ("x", x), ("y", y)):
        out.append("static const unsigned char v%d_%s[%d] = {%s};" % (k, name, nb, ",".join(str(b) for b in v.to_bytes(nb, "big"))))
    vecs.append("{%d, %dUL, v%d_n, v%d_x, v%d_y}" % (bits, e, k, k, k))
out.append("static const VEC vecs[] = {%s};" % ", ".join(vecs))
open("testvec.h", "w").write("\n".join(out) + "\n")
