# test vectors and the DSP program for TLSDSP.PRG
import random, sys
random.seed(1)
M = (1 << 23) - 1
def limbs(x, n): return [(x >> (23 * i)) & M for i in range(n)]
def cios(a, b, m, mp, n):
    t = [0] * (n + 2)
    for i in range(n):
        C = 0
        for j in range(n):
            s = t[j] + a[j] * b[i] + C; t[j] = s & M; C = s >> 23
        s = t[n] + C; t[n] = s & M; t[n + 1] = s >> 23
        mi = (t[0] * mp) & M
        s = t[0] + mi * m[0]; C = s >> 23
        for j in range(1, n):
            s = t[j] + mi * m[j] + C; t[j - 1] = s & M; C = s >> 23
        s = t[n] + C; t[n - 1] = s & M; C = s >> 23
        t[n] = t[n + 1] + C
    return t[:n + 1]
out = ["/* generated by gen.py */"]
for bits in (2048, 256):
    n = (bits + 22) // 23
    m = random.getrandbits(bits) | (1 << (bits - 1)) | 1
    a = random.randrange(m); b = random.randrange(m)
    mp = (-pow(m, -1, 1 << 23)) & M
    A, B, Mm = limbs(a, n), limbs(b, n), limbs(m, n)
    T = cios(A, B, Mm, mp, n)
    v = sum(x << (23 * i) for i, x in enumerate(T))
    R = 1 << (23 * n)
    assert v % m == a * b * pow(R, -1, m) % m and v < 2 * m
    for name, arr in (("a", A), ("b", B), ("m", Mm), ("t", T)):
        out.append("static const unsigned long v%d_%s[%d] = {%s};" % (bits, name, len(arr), ",".join("0x%06x" % x for x in arr)))
    out.append("#define V%d_N %d\n#define V%d_MP 0x%06x" % (bits, n, bits, mp))
p = [0] * 512
for line in open("a56.out"):
    f = line.split()
    if f and f[0] == "P":
        p[int(f[1], 16)] = int(f[2], 16)
out.append("static const unsigned long dsp_prog[512] = {%s};" % ",".join("0x%06x" % x for x in p))
open("dspvec.h", "w").write("\n".join(out) + "\n")
print("ok", max(i for i, x in enumerate(p) if x))
